BASE_URL = "https://cnt-afacebee-38be-43fb-bbea-47c47380e79d.containerhub.tripleten-services.com/"

class UrbanRoutesData:
    ADDRESS_FROM = "East 2nd Street, 601"
    TO_ADDRESS = "1300 1st St"
    REQUEST_TAXI = "Pedir un taxi"
    SELECT_CATEGORY = "Comfort"
    PHONE_NUMBER = "+12312312312"
    CARD_NUMBER = "1234 0000 4321 1234"
    VERIFICATION_CODE = "123"
    MESSAGE_FOR_DRIVER = "Traer los snacks"
    BLANKETS_AND_TISSUES = "Pedir mantas y pañuelos"
    ICE_CREAMS = "Pedir 2 helados"
    REQUEST_TAXI_AGAIN = "Pedir un taxi otra vez"
    FOR_BENDER = "Esperar que aparezca la figura de bender"